language: node_js
node_js:
  - "10.16.3"
script:
  - echo "Deploy!!"
  - yarn install
  - yarn build
install:
  - npm install -g yarn
  - npm install -g firebase-tools

after_success:
  - firebase deploy --debug --project mgpwastudio --token $token
