language: node_js
node_js:
  - "10.16.3"
script:
  - echo "Deploy!!"
  - npm install
  - npm run build
install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --project mgpwastudio --token $token